[package]
name = "interfaces_github_stargazers"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.98"
reqwest = { version = "0.12.15", features = ["json"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
